# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("--start-maximized")
  driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_untitled(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(796, 816)
    self.driver.find_element(By.ID, "APjFqb").send_keys("google maps")
    self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb").click()
    self.driver.find_element(By.ID, "searchboxinput").click()
    self.driver.find_element(By.ID, "searchboxinput").send_keys("restaurants")
    self.driver.find_element(By.ID, "searchboxinput").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .Nv2PK > .hfpxzc").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".aoRNLd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".J8zHNe").click()
    self.vars["win7374"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win7374"])
    self.driver.find_element(By.CSS_SELECTOR, ".IfyCqb > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sc-kIXKos:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sc-gHpXsY:nth-child(11) > .sc-bOxvsH:nth-child(3) > div:nth-child(2) .sc-eLpfTy:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,12710)")
    self.driver.find_element(By.CSS_SELECTOR, ".sc-dCzMmV").click()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["undefined"])
  
