# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGooglemaps():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_googlemaps(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(796, 816)
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("google map")
    self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fontBodyLarge")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".GFG2E")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".RbwPDd .KNfEk:nth-child(2) .L6Bbsd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "searchboxinput").click()
    self.driver.find_element(By.ID, "searchboxinput").send_keys("hotels near me")
    self.driver.find_element(By.ID, "searchboxinput").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(7) .hfpxzc").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hh2c6:nth-child(2) .a52Cae")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".hh2c6:nth-child(2) .Gpq6kf").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".DxyBCb").click()
    self.vars["win497"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win497"])
    self.driver.execute_script("window.scrollTo(0,44)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "htl_id_seo_202209140346121081").click()
    self.vars["win682"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win682"])
    self.driver.switch_to.window(self.vars["win497"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win682"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".hh2c6:nth-child(1) .Gpq6kf").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".aoRNLd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".aoRNLd > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".x7ME4e .Io6YTe").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".rr4y5c").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".x7ME4e .Io6YTe").click()
    self.driver.close()
  
