# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWikipedia():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wikipedia(self):
    self.driver.get("https://www.wikipedia.org/")
    self.driver.set_window_size(796, 816)
    self.driver.find_element(By.ID, "searchInput").send_keys("what is apple")
    self.driver.find_element(By.ID, "searchInput").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Excursions (1863) Thoreau/Wild Apples").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ws-footer-forward > a").click()
    self.driver.find_element(By.LINK_TEXT, "Return to the top of the page.").click()
    self.driver.find_element(By.LINK_TEXT, "public domain").click()
    self.driver.close()
  
